apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: if6pi14z6-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/if6pi14z6-dotnet-basic-gitops